### ISSUE TITLE
StreamQueue.obj() fails with empty argument list

### ISSUE THREAD

**Issue by kjots** [nfroidure/StreamQueue#9]
`StreamQueue.obj()` will fail with an exception when no arguments are provided.

The following code:

```JavaScript
// test.js
var StreamQueue = require('streamqueue');

StreamQueue.obj();
```

Will result in in the following exception:

```
zaphod-wifi:streamqueue-obj-bug kjots$ node test.js 
/Users/kjots/Development/Temp/streamqueue-obj-bug/node_modules/streamqueue/src/index.js:184
  options.objectMode = true;
                     ^
TypeError: Cannot set property 'objectMode' of undefined
    at Function.streamQueueObj (/Users/kjots/Development/Temp/streamqueue-obj-bug/node_modules/streamqueue/src/index.js:184:22)
    at Object.<anonymous> (/Users/kjots/Development/Temp/streamqueue-obj-bug/test.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
zaphod-wifi:streamqueue-obj-bug kjots$
```

The corresponding non-shortcut function will not produce an exception:

```JavaScript
// test.js
var StreamQueue = require('streamqueue');

StreamQueue({ objectMode: true });
```

```
zaphod-wifi:streamqueue-obj-bug kjots$ node test.js 
zaphod-wifi:streamqueue-obj-bug kjots$
```

(Note that this issue can be worked around by supplying an empty object as the first argument to `StreamQueue.obj()`, however this defeats the purpose of a having a shortcut function in the first place.)

**Comment by nfroidure** [comment]
Thanks for reporting it.
